Estrutura de Dados
(todos os vetores tem que ser do mesmo tipo)

```{r}

# Vetores

vet = c(1,2,3,4,5,6)
vet

vet[1]
vet[1] = 10
vet[1]

vet[2]
vet[2] = 18
vet[2]

```

```{r}

# Vetores de outros tipos

vetCarctere = c("a","b","c","d")
vetCarctere

vetInteiro = c(1L, 2L, 3L)
vetInteiro

```

```{r}

# Matrizes

# VADeaths - matriz que ja vem com o R
VADeaths

# exibe os nomes das colunas
colnames(VADeaths)
# exibe os nomes das linhas
rownames(VADeaths)

```

```{r}

# Matrizes continuando

# só coluna 1
VADeaths[,1]

# só linha 1
VADeaths[1,]

# linhas 1 até 3
VADeaths[1:3,]

# acessando a 1ª, 3ª e 5ª linha
VADeaths[c(1, 3, 5)]

```

```{r}

# Data Frame
# é bem semelhantes as matrizes, mas podem ter tipos de dados diferentes
# acessa os dados da mesma forma, pode ter nomes de linhas ou colunas

longley

# funciona como matriz (acessando todas as linhas coluna 1 até 3)
longley[,1:3]

# acessar dados da coluna que tem ' $ ' (formatação de vetor)
longley$Unemployed

# acessar coluna de nome 'Unemployed' (formatação de coluna)
longley['Unemployed']


```

```{r}

# Listas

ability.cov

# acessando elementos
ability.cov$cov
ability.cov[1]

# verificando que são objetos diferentes
class(ability.cov$cov)
class(ability.cov$center)

# acessando elemento dentro da lista
ability.cov$cov[,1:3]

```

```{r}

# Fatores

state.region
state.area

```



